---
sidebar: sidebar 
permalink: faq-data-classification.html 
keywords: faq, frequently asked questions, questions, cloud compliance, data sense 
summary: 이 FAQ는 질문에 대한 빠른 답변을 찾는 데 도움이 될 수 있습니다. 
---
= NetApp Data Classification에 대한 FAQ
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
이 FAQ를 통해 NetApp Data Classification에 대한 일반적인 질문에 대한 빠른 답변을 찾을 수 있습니다.



[[netapp-data-classification]]
== NetApp Data Classification

다음 질문은 데이터 분류에 대한 일반적인 이해를 제공합니다.



[[how-does-data-classification-work]]
=== 데이터 분류는 어떻게 작동하나요?

데이터 분류는 NetApp Console 시스템 및 스토리지 시스템과 함께 또 다른 AI 계층을 배포합니다. 볼륨, 버킷, 데이터베이스 및 기타 스토리지 계정의 데이터를 스캔하고 발견된 데이터 인사이트를 인덱싱합니다. 데이터 분류는 정규 표현식 및 패턴 매칭을 기반으로 구축된 기존 솔루션과 달리 인공지능과 자연어 처리를 모두 활용합니다.

Data Classification은 AI를 활용하여 데이터에 대한 맥락적 이해를 바탕으로 정확한 탐지 및 분류를 수행합니다. 최신 데이터 유형과 규모에 맞춰 설계되었기 때문에 AI 기반으로 구동됩니다. 또한 데이터의 맥락을 파악하여 정확하고 강력한 탐지 및 분류 결과를 제공합니다.

link:concept-classification.html["데이터 분류가 작동하는 방식에 대해 자세히 알아보세요"] .



[[does-data-classification-have-a-rest-api-and-does-it-work-with-third-party-tools]]
=== 데이터 분류에 REST API가 있나요? 타사 도구와도 호환되나요?

네, 데이터 분류에는 콘솔 핵심 플랫폼의 일부인 데이터 분류 버전의 지원되는 기능에 대한 REST API가 있습니다. 보다 link:api-classification.html["API 문서"] .



[[is-data-classification-available-through-the-cloud-marketplaces]]
=== 클라우드 마켓플레이스를 통해 데이터 분류를 이용할 수 있나요?

데이터 분류는 NetApp Console의 핵심 기능에 포함되어 있습니다. 클라우드 마켓플레이스에서 데이터 분류 기능을 배포할 필요가 없습니다.



[[data-classification-scanning-and-analytics]]
== 데이터 분류 스캐닝 및 분석

다음 질문은 데이터 분류 스캐닝 성능과 분석과 관련이 있습니다.



[[how-often-does-data-classification-scan-my-data]]
=== 데이터 분류는 얼마나 자주 데이터를 스캔합니까?

데이터를 처음 검사하는 데는 시간이 조금 걸릴 수 있지만, 이후 검사에서는 증분적인 변경 사항만 검사하므로 시스템 검사 시간이 줄어듭니다.  데이터 분류는 한 번에 6개의 저장소에서 라운드 로빈 방식으로 데이터를 지속적으로 스캔하므로 변경된 모든 데이터가 매우 빠르게 분류됩니다.

link:task-scanning-overview.html["스캔 작동 방식 알아보기"] .

데이터 분류는 하루에 한 번만 데이터베이스를 스캔합니다. 데이터베이스는 다른 데이터 소스처럼 지속적으로 스캔되지 않습니다.

데이터 스캔은 저장 시스템과 데이터에 미치는 영향이 미미합니다.



[[does-scan-performance-vary]]
=== 스캔 성능은 다양합니까?

스캔 성능은 네트워크 대역폭과 환경의 평균 파일 크기에 따라 달라질 수 있습니다. 또한 호스트 시스템의 크기와 위치(클라우드 또는 온프레미스 여부)에 따라서도 달라질 수 있습니다. 자세한 내용은 link:concept-classification.html["데이터 분류 인스턴스"] 및 link:task-deploy-overview.html["데이터 분류 배포"]을 참조하십시오.

새로운 데이터 소스를 처음 추가할 때 매핑 전용 스캔만 수행하거나 전체 스캔을 수행할지 선택할 수 있습니다. 매핑은 파일에 액세스하여 내부 데이터를 확인하지 않으므로 데이터 소스에서 매우 빠르게 수행할 수 있습니다. link:task-scanning-overview.html["매핑 스캔과 분류 스캔의 차이점을 이해하십시오"].



[[can-i-search-my-data-using-data-classification]]
=== 데이터 분류를 사용하여 데이터를 검색할 수 있나요?

데이터 분류는 모든 연결된 소스에서 특정 파일이나 데이터를 쉽게 검색할 수 있는 광범위한 검색 기능을 제공합니다.  데이터 분류를 통해 사용자는 메타데이터가 반영하는 것 이상의 심층적인 검색을 수행할 수 있습니다.  이름, ID 등 다양한 민감한 데이터 유형을 읽고 분석할 수 있는 언어에 구애받지 않는 서비스입니다.  예를 들어, 사용자는 구조화된 데이터 저장소와 구조화되지 않은 데이터 저장소를 모두 검색하여 회사 정책을 위반하여 데이터베이스에서 사용자 파일로 유출되었을 수 있는 데이터를 찾을 수 있습니다.  검색 결과는 나중에 사용할 수 있도록 저장할 수 있으며, 정책을 만들어서 일정 빈도로 검색 결과를 검색하고 조치를 취할 수 있습니다.

관심 있는 파일을 찾으면 태그, 시스템 계정, 버킷, 파일 경로, 범주(분류에서 가져옴), 파일 크기, 마지막 수정, 권한 상태, 중복, 민감도 수준, 개인 데이터, 파일 내의 민감한 데이터 유형, 소유자, 파일 유형, 파일 크기, 생성 시간, 파일 해시, 데이터가 주의를 끌기 위해 누군가에게 할당되었는지 여부 등의 특성을 나열할 수 있습니다.  필터를 적용하면 관련성이 없는 특성을 걸러낼 수 있습니다.

데이터 분류에는 역할 기반 액세스 제어(RBAC) 기능도 있어 적절한 권한이 있는 경우 파일을 이동하거나 삭제할 수 있습니다.  적절한 권한이 없는 경우, 해당 작업은 조직 내에서 적절한 권한이 있는 사람에게 할당될 수 있습니다.



[[if-i-restart-my-vm-during-scans-what-is-the-impact-on-the-scan]]
=== 스캔 도중에 VM을 재시작하면 스캔에 어떤 영향이 있습니까?

검사는 계속 진행됩니다. 검사가 실행 중인 동안 가상 머신을 다시 시작하면 가상 머신이 성공적으로 재부팅된 후 중단된 부분부터 검사가 재개됩니다.



[[data-classification-management-and-privacy]]
== 데이터 분류 관리 및 개인 정보 보호

다음 질문은 데이터 분류 및 개인정보 보호 설정을 관리하는 방법에 대한 정보를 제공합니다.



[[how-do-i-enable-or-disable-data-classification]]
=== 데이터 분류를 활성화하거나 비활성화하려면 어떻게 해야 하나요?

먼저 콘솔이나 온프레미스 시스템에 데이터 분류 인스턴스를 배포해야 합니다.  인스턴스가 실행되면 *구성* 탭에서 또는 특정 시스템을 선택하여 기존 시스템, 데이터베이스 및 기타 데이터 소스에서 서비스를 활성화할 수 있습니다. link:task-getting-started-compliance.html["시작하는 방법을 알아보세요"] .


NOTE: 데이터 소스에서 데이터 분류를 활성화하면 즉각적인 초기 검사가 수행됩니다.  검사 결과는 곧 표시됩니다.

데이터 분류 구성 페이지에서 개별 시스템, 데이터베이스 또는 파일 공유 그룹을 스캔하는 데이터 분류를 비활성화할 수 있습니다. 보다 link:task-managing-compliance.html["데이터 분류에서 데이터 소스 제거"] .

데이터 분류 인스턴스를 완전히 제거하려면 클라우드 공급자 포털 또는 온프레미스 위치에서 데이터 분류 인스턴스를 수동으로 제거하십시오.



[[can-the-service-exclude-scanning-data-in-certain-directories]]
=== 이 서비스는 특정 디렉토리의 스캐닝 데이터를 제외할 수 있나요?

네. 특정 데이터 소스 디렉토리에 있는 스캐닝 데이터를 데이터 분류에서 제외하려면 분류 엔진에 해당 목록을 제공하면 됩니다.  해당 변경 사항을 적용하면 데이터 분류에서 지정된 디렉토리의 스캐닝 데이터가 제외됩니다. link:task-exclude-scan-paths.html["자세히 알아보기"] .



[[are-snapshots-that-reside-on-ontap-volumes-scanned]]
=== ONTAP 볼륨에 있는 스냅샷이 스캔되나요?

아니요. 데이터 분류는 스냅샷을 스캔하지 않습니다. 콘텐츠가 볼륨의 콘텐츠와 동일하기 때문입니다.



[[what-happens-if-data-tiering-is-enabled-on-your-ontap-volumes]]
=== ONTAP 볼륨에서 데이터 계층화가 활성화되면 어떻게 되나요?

데이터 분류 기능이 맵 전용 스캔을 사용하여 콜드 데이터가 객체 스토리지로 계층화된 볼륨을 스캔할 때, 로컬 디스크의 데이터와 객체 스토리지로 계층화된 콜드 데이터를 포함한 모든 데이터를 스캔합니다. 이는 계층화를 구현하는 NetApp 제품이 아닌 경우에도 마찬가지입니다.

맵 전용 스캔은 콜드 데이터를 워밍업하지 않습니다. 콜드 데이터는 그대로 오브젝트 스토리지에 저장됩니다. 반면 전체 스캔을 수행하는 경우, 일부 구성에서는 콜드 데이터가 워밍업될 수 있습니다.



[[types-of-source-systems-and-data-types]]
== 소스 시스템 및 데이터 유형의 유형

다음 질문은 스캔할 수 있는 저장소 유형과 스캔되는 데이터 유형과 관련이 있습니다.



[[are-there-any-restrictions-when-deployed-in-a-government-region]]
=== 정부 지역에 배치될 때 제한 사항이 있나요?

콘솔 에이전트가 정부 지역(AWS GovCloud, Azure Gov 또는 Azure DoD)에 배포된 경우 데이터 분류가 지원됩니다. 이를 "제한 모드"라고도 합니다.



[[what-data-sources-can-i-scan-if-i-install-data-classification-in-a-site-without-internet-access]]
=== 인터넷 접속이 불가능한 사이트에 데이터 분류를 설치하면 어떤 데이터 소스를 스캔할 수 있나요?

데이터 분류는 온프레미스 사이트의 로컬 데이터 소스에서만 데이터를 스캔할 수 있습니다.  현재 데이터 분류는 다음과 같은 로컬 데이터 소스를 "비공개 모드"(다크 사이트라고도 함)에서 스캔할 수 있습니다.

* 온프레미스 ONTAP 시스템
* 데이터베이스 스키마
* S3(Simple Storage Service) 프로토콜을 사용하는 개체 스토리지




[[which-file-types-are-supported]]
=== 어떤 파일 형식이 지원되나요?

데이터 분류는 모든 파일을 스캔하여 범주 및 메타데이터에 대한 통찰력을 제공하고 대시보드의 파일 유형 섹션에 모든 파일 유형을 표시합니다.

데이터 분류 기능이 개인 식별 정보(PII)를 감지하거나 DSAR 검색을 수행할 때 지원되는 파일 형식은 다음과 같습니다.

`+.CSV, .DCM, .DOC, .DOCX, .JSON, .PDF, .PPTX, .RTF, .TXT, .XLS, .XLSX, Docs, Sheets, and Slides+`



[[what-kinds-of-data-and-metadata-does-data-classification-capture]]
=== 데이터 분류는 어떤 종류의 데이터와 메타데이터를 수집합니까?

데이터 분류 기능을 사용하면 데이터 소스에 대해 맵 전용 스캔 또는 전체 스캔을 실행할 수 있습니다. 맵 전용 스캔은 데이터에 대한 개략적인 정보만 제공하는 반면, 전체 스캔은 데이터에 대한 심층적인 스캔을 제공합니다. 맵 전용 스캔은 파일 내부의 데이터를 확인하기 위해 파일에 액세스하지 않으므로 데이터 소스를 매우 빠르게 처리할 수 있습니다.

* *데이터 매핑 스캔(매핑 전용 스캔)*: 데이터 분류는 메타데이터만 스캔합니다.  이는 전반적인 데이터 관리 및 거버넌스, 신속한 프로젝트 범위 설정, 대규모 자산 및 우선 순위 지정에 유용합니다.  데이터 매핑은 메타데이터를 기반으로 하며 *빠른* 스캔으로 간주됩니다.
+
빠른 검사 후 데이터 매핑 보고서를 생성할 수 있습니다.  이 보고서는 기업 데이터 소스에 저장된 데이터에 대한 개요를 제공하며, 이를 통해 리소스 활용, 마이그레이션, 백업, 보안 및 규정 준수 프로세스에 대한 의사 결정을 내리는 데 도움이 됩니다.

* *데이터 분류 심층 검사(전체 검사)*: 데이터 분류는 표준 프로토콜과 읽기 전용 권한을 사용하여 환경 전체의 데이터를 검사합니다. 선택된 파일을 열어 민감한 비즈니스 관련 데이터, 개인 정보 및 랜섬웨어 관련 문제를 검사합니다.
+
전체 검사 후에는 데이터 조사 페이지에서 데이터 보기 및 세분화, 파일 내에서 이름 검색, 소스 파일 복사, 이동 및 삭제 등 데이터에 적용할 수 있는 추가 데이터 분류 기능이 많이 있습니다.



데이터 분류는 파일 이름, 권한, 생성 시간, 마지막 액세스 및 마지막 수정과 같은 메타데이터를 캡처합니다. 여기에는 데이터 조사 세부 정보 페이지 및 데이터 조사 보고서에 나타나는 모든 메타데이터가 포함됩니다.

데이터 분류를 통해 개인 정보(PII) 및 민감한 개인 정보(SPII) 등 다양한 유형의 비공개 데이터를 식별할 수 있습니다.  개인 정보에 대한 자세한 내용은 다음을 참조하세요.xref:reference-private-data-categories.html[데이터 분류가 스캔하는 개인 데이터 범주] .



[[can-i-limit-data-classification-information-to-specific-users]]
=== 데이터 분류 정보를 특정 사용자에게만 제한할 수 있나요?

네, 데이터 분류는 NetApp Console 과 완벽하게 통합되어 있습니다.  NetApp Console 사용자는 자신의 권한에 따라 볼 수 있는 시스템에 대한 정보만 볼 수 있습니다.

또한, 특정 사용자가 데이터 분류 설정을 관리할 수 없도록 데이터 분류 검사 결과만 볼 수 있도록 허용하려면 해당 사용자에게 *분류 뷰어* 역할( NetApp Console 표준 모드로 사용하는 경우) 또는 *규정 준수 뷰어* 역할( NetApp Console 제한 모드로 사용하는 경우)을 할당할 수 있습니다. link:concept-classification.html["자세히 알아보기"] .



[[can-anyone-access-the-private-data-sent-between-my-browser-and-data-classification]]
=== 내 브라우저와 데이터 분류 간에 전송되는 개인 데이터에 누구든지 접근할 수 있나요?

아니요. 브라우저와 데이터 분류 인스턴스 간에 전송되는 개인 데이터는 TLS 1.2를 사용한 종단 간 암호화로 보호되므로 NetApp 및 제3자는 해당 데이터를 읽을 수 없습니다. 데이터 분류는 사용자가 액세스를 요청하고 승인하지 않는 한 NetApp과 어떠한 데이터나 결과도 공유하지 않습니다.

스캔된 데이터는 사용자 환경 내에 유지됩니다.



[[how-is-sensitive-data-handled]]
=== 민감한 데이터는 어떻게 처리되나요?

NetApp 민감한 데이터에 액세스할 수 없으며 이를 UI에 표시하지 않습니다.  민감한 데이터는 가려집니다. 예를 들어, 신용카드 정보의 경우 마지막 4자리 숫자가 표시됩니다.



[[where-is-the-data-stored]]
=== 데이터는 어디에 저장되나요?

검사 결과는 데이터 분류 인스턴스 내의 Elasticsearch에 저장됩니다.



[[how-is-the-data-accessed]]
=== 데이터에 어떻게 접근하나요?

데이터 분류는 API 호출을 통해 Elasticsearch에 저장된 데이터에 액세스하는데, 이 때 인증이 필요하고 AES-128을 사용하여 암호화됩니다.  Elasticsearch에 직접 액세스하려면 루트 액세스가 필요합니다.



[[licenses-and-costs]]
== 라이센스 및 비용

다음 질문은 데이터 분류 사용에 따른 라이선스 및 비용과 관련이 있습니다.



[[how-much-does-data-classification-cost]]
=== 데이터 분류 비용은 얼마인가요?

데이터 분류는 NetApp Console 핵심 기능입니다.  충전되지 않았습니다.



[[console-agent-deployment]]
== 콘솔 에이전트 배포

다음 질문은 콘솔 에이전트와 관련이 있습니다.



[[what-is-the-console-agent]]
=== 콘솔 에이전트란 무엇인가요?

콘솔 에이전트는 클라우드 계정 내부 또는 온프레미스의 컴퓨팅 인스턴스에서 실행되는 소프트웨어로, NetApp Console 클라우드 리소스를 안전하게 관리할 수 있도록 해줍니다.  데이터 분류를 사용하려면 콘솔 에이전트를 배포해야 합니다.



[[where-does-the-console-agent-need-to-be-installed]]
=== 콘솔 에이전트는 어디에 설치해야 합니까?

데이터를 스캔할 때 NetApp Console 에이전트는 다음 위치에 설치해야 합니다.

* AWS의 Cloud Volumes ONTAP 또는 Amazon FSx for ONTAP 의 경우: 콘솔 에이전트가 AWS에 있습니다.
* Azure 또는 Azure NetApp Files 의 Cloud Volumes ONTAP 의 경우: 콘솔 에이전트가 Azure에 있습니다.
* GCP의 Cloud Volumes ONTAP 의 경우: 콘솔 에이전트가 GCP에 있습니다.
* 온프레미스 ONTAP 시스템의 경우: 콘솔 에이전트는 온프레미스에 있습니다.


이러한 위치에 데이터가 있는 경우 다음을 사용해야 할 수 있습니다. https://docs.netapp.com/us-en/console-setup-admin/concept-connectors.html#when-to-use-multiple-connectors["여러 콘솔 에이전트"^] .



[[does-data-classification-require-access-to-credentials]]
=== 데이터 분류에 자격 증명에 대한 액세스가 필요합니까?

데이터 분류 자체는 저장소 자격 증명을 검색하지 않습니다.  대신 콘솔 에이전트에 저장됩니다.

데이터 분류는 스캔하기 전에 공유를 마운트하기 위해 CIFS 자격 증명과 같은 데이터 플레인 자격 증명을 사용합니다.



[[does-communication-between-the-service-and-the-console-agent-use-http]]
=== 서비스와 콘솔 에이전트 간의 통신은 HTTP를 사용합니까?

네, 데이터 분류는 HTTP를 사용하여 콘솔 에이전트와 통신합니다.



[[data-classification-deployment]]
== 데이터 분류 배포

다음 질문은 별도의 데이터 분류 인스턴스와 관련이 있습니다.



[[what-deployment-models-does-data-classification-support]]
=== 데이터 분류는 어떤 배포 모델을 지원합니까?

NetApp Console을 사용하면 온프레미스, 클라우드 및 하이브리드 환경을 포함하여 사실상 모든 곳에서 시스템을 스캔하고 보고할 수 있습니다. Data Classification은 일반적으로 SaaS 모델로 배포되며, Console 인터페이스를 통해 서비스를 활성화할 수 있고 하드웨어 또는 소프트웨어 설치가 필요하지 않습니다. 이러한 클릭 앤 런 방식의 배포 모드에서도 데이터 저장소가 온프레미스에 있든 퍼블릭 클라우드에 있든 관계없이 데이터 관리를 수행할 수 있습니다.



[[what-type-of-instance-or-vm-is-required-for-data-classification]]
=== 데이터 분류에는 어떤 유형의 인스턴스 또는 VM이 필요합니까?

언제link:task-deploy-cloud-compliance.html["클라우드에 배포됨"] :

* AWS에서 Data Classification은 500GiB GP2 디스크가 장착된 m6i.4xlarge 인스턴스에서 실행됩니다.
* Azure에서 데이터 분류는 500GiB 디스크가 있는 Standard_D16s_v3 VM에서 실행됩니다.
* GCP에서 데이터 분류는 500GiB Standard 영구 디스크가 있는 n2-standard-16 VM에서 실행됩니다.


link:concept-classification.html["데이터 분류가 작동하는 방식에 대해 자세히 알아보세요"] .



[[can-i-deploy-the-data-classification-on-my-own-host]]
=== 내 호스트에 데이터 분류를 배포할 수 있나요?

네. 네트워크나 클라우드에서 인터넷 접속이 가능한 Linux 호스트에 데이터 분류 소프트웨어를 설치할 수 있습니다.  모든 것이 동일하게 작동하며 콘솔을 통해 스캔 구성과 결과를 계속 관리할 수 있습니다.  보다link:task-deploy-compliance-onprem.html["온프레미스에 데이터 분류 배포"] 시스템 요구 사항 및 설치 세부 정보를 확인하세요.



[[what-about-secure-sites-without-internet-access]]
=== 인터넷 접속이 불가능한 보안 사이트는 어떻게 되나요?

네, 그것도 지원됩니다.  당신은 할 수 있습니다link:task-deploy-compliance-dark-site.html["인터넷 접속이 불가능한 온프레미스 사이트에 데이터 분류 배포"] 완벽하게 안전한 사이트를 위해.
