---
sidebar: sidebar 
permalink: reference-limitations.html 
keywords: limitations, data sense, classification, scan shares 
summary: 알려진 제한 사항은 이 제품 릴리스에서 지원하지 않거나 올바르게 상호 운용되지 않는 기능을 나타냅니다. 이러한 제한 사항을 주의 깊게 검토하세요. 
---
= NetApp 데이터 분류의 알려진 제한 사항
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
알려진 제한 사항은 이 릴리스에서 지원되지 않거나 올바르게 상호 운용되지 않는 기능을 나타냅니다. 이러한 제한 사항을 주의 깊게 검토하세요.



== NetApp 데이터 분류 비활성화 옵션

2023년 12월(버전 1.26.6) 릴리스에서는 다음 옵션이 제거되었습니다.

* 감사 로그 수집을 활성화하는 옵션이 비활성화되었습니다.
* 디렉토리 조사 중에 디렉토리별 개인 식별 정보(PII) 데이터 수를 계산하는 옵션을 사용할 수 없습니다.
* Azure Information Protection(AIP) 레이블을 사용하여 데이터를 통합하는 옵션이 비활성화되었습니다.




== 데이터 분류 스캐닝

데이터 분류 스캔에는 다음과 같은 제한 사항이 있습니다.



=== 데이터 분류는 볼륨 아래의 단 하나의 공유만 스캔합니다.

단일 볼륨 아래에 여러 개의 파일 공유가 있는 경우 데이터 분류는 계층 구조가 가장 높은 공유를 스캔합니다.  예를 들어, 다음과 같은 주식이 있다고 가정해 보겠습니다.

* /에이
* /A/B
* /기음
* /디/이


이 구성에서는 /A의 데이터만 스캔됩니다.  /C와 /D의 데이터는 스캔되지 않습니다.

.해결 방법
볼륨의 모든 공유에서 데이터를 스캔하고 있는지 확인하는 해결 방법이 있습니다. 다음 단계를 따르세요.

. 시스템에서 스캔할 볼륨을 추가합니다.
. 데이터 분류가 볼륨 스캔을 완료한 후 _데이터 조사_ 페이지로 이동하여 스캔 중인 공유를 확인하기 위한 필터를 만듭니다.
+
"시스템 이름"과 "디렉토리 유형 = 공유"로 데이터를 필터링하여 어떤 공유가 스캔되고 있는지 확인하세요.

. 볼륨에 존재하는 주식의 전체 목록을 가져와서 스캔되지 않은 주식이 무엇인지 확인하세요.
. link:task-scanning-file-shares.html["나머지 주식을 공유 그룹에 추가합니다."] .
+
예를 들어, 모든 주식을 개별적으로 추가합니다.

+
....
/C
/D
....
. 여러 공유가 있는 시스템의 각 볼륨에 대해 이 단계를 수행합니다.




=== 마지막으로 액세스한 타임스탬프

데이터 분류가 디렉토리를 스캔할 때, 해당 스캔은 디렉토리의 **마지막 액세스** 필드에 영향을 미칩니다.  **마지막으로 접근한 날짜** 필드를 보면 해당 메타데이터는 스캔 날짜와 시간 또는 사용자가 디렉토리에 마지막으로 접근한 시간을 반영합니다.
