---
sidebar: sidebar 
permalink: task-deploy-overview.html 
keywords: cloud compliance, data sense, get started, deploy cloud data sense, outbound internet, endpoints, cloud compliance internet, web browser connectivity, cloud compliance access, privacy, compliance, bluexp classification 
summary: 귀하의 요구 사항에 맞는 NetApp Data Classification 배포를 계획하세요. 
---
= NetApp Data Classification 배포 방법
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp Data Classification은 다양한 네트워크 및 연결 요구 사항에 맞춰 여러 배포 방법을 지원합니다. 사용 가능한 방법을 검토하여 환경에 가장 적합한 옵션을 선택하십시오.

* link:task-deploy-cloud-compliance.html["콘솔을 사용하여 클라우드에 배포"] . 콘솔은 콘솔 에이전트와 동일한 클라우드 공급자 네트워크에 데이터 분류 인스턴스를 배포합니다.
* link:task-deploy-compliance-onprem.html["인터넷 접속이 가능한 Linux 호스트에 설치"]. 네트워크 또는 클라우드의 Linux 호스트에 Data Classification을 설치하십시오. 이 옵션은 온프레미스에 있는 Data Classification 인스턴스에서 온프레미스 ONTAP 시스템을 스캔하려는 경우 유용할 수 있지만, 인스턴스를 온프레미스에 배치하는 것이 필수 사항은 아닙니다.
* link:task-deploy-compliance-dark-site.html["인터넷 접속이 불가능한 온프레미스 사이트의 Linux 호스트에 설치"], 이를 _프라이빗 모드_ 라고 합니다. 설치 스크립트를 사용하는 이 설치 유형은 Console SaaS 계층과 연결되지 않습니다.



TIP: 온프레미스 VMware vSphere 배포의 경우 Data Classification은 간소화된 link:task-deploy-ova.html["OVA를 사용한 배포"]을 지원합니다.



[[on-premises-installation-script]]
== 온프레미스 설치 스크립트

두 설치 방법 모두 설치 스크립트를 사용합니다. 스크립트는 시스템 및 환경이 필수 조건을 충족하는지 확인합니다. 조건을 충족하면 설치가 시작됩니다.

Linux 호스트가 준비되었는지 확인하는 데 사용할 수 있는 별도의 소프트웨어 패키지가 있습니다. 확인 패키지를 실행하려면 link:task-test-linux-system.html["Linux 호스트에 NetApp Data Classification을 설치할 준비가 되었는지 확인하십시오"]을 참조하십시오.
