---
sidebar: sidebar 
permalink: task-scanning-overview.html 
keywords: cloud compliance, get started, enable cloud compliance, cifs credentials, smb credentials, cloud compliance access, privacy, compliance, dp volumes, data protection volumes, CVO, Cloud Volumes ONTAP, data sense, cloud data sense, map-only scans, map and classify, full 
summary: NetApp Data Classification 사용하여 데이터 소스를 스캔하세요. 
---
= NetApp Data Classification 사용하여 데이터 소스 스캔
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp Data Classification은 사용자가 선택한 리포지토리(볼륨, 데이터베이스 스키마 또는 기타 사용자 데이터)의 데이터를 스캔하여 개인 정보 및 민감한 데이터를 식별합니다. Data Classification은 조직 데이터를 매핑하고 각 파일을 범주화하며 데이터에서 미리 정의된 패턴을 식별합니다. 스캔 결과는 개인 정보, 민감한 개인 정보, 데이터 범주 및 파일 유형의 인덱스입니다.

초기 스캔 후, 데이터 분류 기능은 점진적인 변화를 감지하기 위해 라운드 로빈 방식으로 데이터를 지속적으로 스캔합니다. 스캔은 매일 자동으로 수행됩니다. 데이터 분류 기능은 6개씩 일괄적으로 스캔을 진행하며, 스캔을 일시 중지하거나 link:task-managing-repo-scanning.html#prioritize-scans["수동으로 우선순위를 지정합니다"].

볼륨 수준이나 데이터베이스 스키마 수준에서 검사를 활성화하거나 비활성화할 수 있습니다.



[[understand-scan-types]]
== 스캔 유형 이해

데이터 분류에서는 두 가지 유형의 스캔을 수행할 수 있습니다.

* **매핑 전용 스캔**은 데이터에 대한 개략적인 개요만 제공하며 선택한 데이터 소스에서 수행됩니다. 매핑 전용 스캔은 내부 데이터를 확인하기 위해 파일에 액세스하지 않으므로 전체 스캔보다 시간이 덜 걸립니다.
* **전체 스캔**은 데이터에 대한 심층적인 스캔을 제공합니다. 전체 스캔에는 매핑 스캔과 파일 내 데이터 분류가 포함됩니다.



TIP: 맵 전용 스캔을 수행하면 데이터 개요를 파악하는 데 도움이 될 수 있습니다. 이렇게 얻은 개괄적인 정보를 바탕으로 전체 스캔을 수행할 데이터 소스를 결정할 수 있습니다.

표를 검토하여 맵 전용 스캔과 전체 스캔에서 어떤 정보가 표시되는지 확인하십시오.

[cols="47,18,18"]
|===
| 특징 | 전체 스캔 | 맵 전용 스캔 


| 스캔 속도 | 느린 | 빠른 


| 가격 | 무료 | 무료 


| 용량 | 500TiB*로 제한됨 | 500TiB*로 제한됨 


| 파일 유형 및 사용 용량 목록 | 예 | 예 


| 파일 개수 및 사용 용량 | 예 | 예 


| 파일의 나이와 크기 | 예 | 예 


| 실행할 수 있는 능력link:task-controlling-governance-data.html["데이터 매핑 보고서"] | 예 | 예 


| 파일 세부 정보를 보려면 데이터 조사 페이지로 이동하세요. | 예 | 아니요 


| 파일 내에서 이름 검색 | 예 | 아니요 


| 만들다link:task-using-policies.html["저장된 쿼리"] 사용자 정의 검색 결과를 제공하는 | 예 | 아니요 


| 다른 보고서를 실행하는 기능 | 예 | 아니요 


| 파일의 메타데이터를 볼 수 있는 기능** | 예 | 예 
|===
{asterisk} Data Classification은 스캔하는 데이터 양에 제한을 두지 않습니다. 각 Console 에이전트는 500TiB의 데이터 스캔 및 표시를 지원합니다. 500TiB 이상의 데이터를 스캔하려면 link:https://docs.netapp.com/us-en/console-setup-admin/concept-connectors.html#connector-installation["다른 콘솔 에이전트를 설치하세요"^] 다음 link:task-deploy-overview.html["다른 데이터 분류 인스턴스 배포"]. + Console UI는 단일 커넥터의 데이터를 표시합니다. 여러 Console 에이전트의 데이터 보기에 대한 팁은 link:https://docs.netapp.com/us-en/console-setup-admin/task-manage-multiple-connectors.html#switch-between-connectors["여러 콘솔 에이전트와 함께 작업"^]을 참조하십시오.

{별표}{별표} 매핑 스캔 중에 파일에서 다음 메타데이터가 추출됩니다.

* 파일 발견 시간
* 파일 마지막 액세스 시간
* 파일이 마지막으로 수정되었습니다
* 파일 유형
* 파일 크기
* 파일 생성
* 파일 수
* 권한 추출
* 저장 저장소
* 체계
* 시스템 유형
* 사용된 용량


.거버넌스 대시보드 차이점:
[%collapsible]
====
[cols="40,25,25"]
|===
| 특징 | 전체 스캔 | 맵 전용 스캔 


| 오래된 데이터 | 예 | 예 


| 비업무용 데이터 | 예 | 예 


| 중복된 파일 | 예 | 예 


| 미리 정의된 저장된 쿼리 | 예 | 아니요 


| 기본 저장된 쿼리 | 예 | 예 


| DDA 보고서 | 예 | 예 


| 매핑 보고서 | 예 | 예 


| 감도 수준 감지 | 예 | 아니요 


| 광범위한 권한이 있는 민감한 데이터 | 예 | 아니요 


| 공개 권한 | 예 | 예 


| 데이터의 시대 | 예 | 예 


| 데이터 크기 | 예 | 예 


| 카테고리 | 예 | 아니요 


| 파일 유형 | 예 | 예 
|===
====
.규정 준수 대시보드 차이점:
[%collapsible]
====
[cols="40,25,25"]
|===
| 특징 | 전체 스캔 | 맵 전용 스캔 


| 개인정보 | 예 | 아니요 


| 민감한 개인 정보 | 예 | 아니요 


| 개인정보 위험 평가 보고서 | 예 | 아니요 


| HIPAA 보고서 | 예 | 아니요 


| PCI DSS 보고서 | 예 | 아니요 
|===
====
.조사 필터의 차이점은 다음과 같습니다.
[%collapsible]
====
[cols="40,25,25"]
|===
| 특징 | 전체 스캔 | 맵 전용 스캔 


| 저장된 쿼리 | 예 | 예 


| 시스템 유형 | 예 | 예 


| 체계 | 예 | 예 


| 저장 저장소 | 예 | 예 


| 파일 유형 | 예 | 예 


| 파일 크기 | 예 | 예 


| 생성 시간 | 예 | 예 


| 발견된 시간 | 예 | 예 


| 마지막 수정 | 예 | 예 


| 마지막 접속 | 예 | 예 


| 공개 권한 | 예 | 예 


| 파일 디렉토리 경로 | 예 | 예 


| 범주 | 예 | 아니요 


| 민감도 수준 | 예 | 아니요 


| 식별자의 수 | 예 | 아니요 


| 개인정보 | 예 | 아니요 


| 민감한 개인 데이터 | 예 | 아니요 


| 데이터 주체 | 예 | 아니요 


| 중복 | 예 | 예 


| 분류 상태 | 예 | 상태는 항상 "제한된 통찰력"입니다. 


| 스캔 분석 이벤트 | 예 | 예 


| 파일 해시 | 예 | 예 


| 접근 권한이 있는 사용자 수 | 예 | 예 


| 사용자/그룹 권한 | 예 | 예 


| 파일 소유자 | 예 | 예 


| 디렉토리 유형 | 예 | 예 
|===
====