---
sidebar: sidebar 
permalink: task-active-directory.html 
keywords: active directory, ad, data sense, cloud data sense 
summary: NetApp Data Classification 와 글로벌 Active Directory를 통합하면 데이터 분류 보고서에서 파일 소유자와 파일에 액세스할 수 있는 사용자 및 그룹에 대한 결과를 더욱 향상시킬 수 있습니다. 
---
= Active Directory와 NetApp Data Classification 통합
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp Data Classification 와 글로벌 Active Directory를 통합하면 데이터 분류 보고서에서 파일 소유자와 파일에 액세스할 수 있는 사용자 및 그룹에 대한 결과를 더욱 향상시킬 수 있습니다.

특정 데이터 소스(아래 나열됨)를 설정하는 경우 데이터 분류가 CIFS 볼륨을 스캔할 수 있도록 Active Directory 자격 증명을 입력해야 합니다.  이 통합은 데이터 분류에 해당 데이터 소스에 있는 데이터의 파일 소유자 및 권한 세부 정보를 제공합니다.  해당 데이터 소스에 대해 입력한 Active Directory는 여기에 입력한 글로벌 Active Directory 자격 증명과 다를 수 있습니다.  데이터 분류는 모든 통합 Active Directory에서 사용자 및 권한 세부 정보를 찾습니다.

이 통합은 데이터 분류의 다음 위치에 추가 정보를 제공합니다.

* "파일 소유자"를 사용할 수 있습니다link:task-investigate-data.html["필터"] 조사 창에서 파일 메타데이터에서 결과를 확인하세요.  SID(보안 식별자)를 포함하는 파일 소유자 대신 실제 사용자 이름이 채워집니다.
+
파일 소유자에 대한 자세한 정보(계정 이름, 이메일 주소, SAM 계정 이름)를 보거나 해당 사용자가 소유한 항목을 볼 수도 있습니다.

* "모든 권한 보기" 버튼을 선택하면 각 파일 및 디렉터리에 대한 link:task-investigate-data.html["전체 파일 권한"]를 확인할 수 있습니다.
* 에서link:task-controlling-governance-data.html["거버넌스 대시보드"] , 공개 권한 패널에는 데이터에 대한 더 자세한 정보가 표시됩니다.



NOTE: 로컬 사용자 SID와 알 수 없는 도메인의 SID는 실제 사용자 이름으로 변환되지 않습니다.



[[supported-data-sources]]
== 지원되는 데이터 소스

데이터 분류와 Active Directory를 통합하면 다음 데이터 소스에서 데이터를 식별할 수 있습니다.

* Azure NetApp Files
* Cloud Volumes ONTAP
* ONTAP 용 FSx
* 온프레미스 ONTAP 시스템




[[connect-to-your-active-directory-server]]
== Active Directory 서버에 연결

데이터 분류를 배포하고 데이터 소스에 대한 스캐닝을 활성화한 후에는 데이터 분류를 Active Directory와 통합할 수 있습니다.  Active Directory는 DNS 서버 IP 주소나 LDAP 서버 IP 주소를 사용하여 액세스할 수 있습니다.

Active Directory 자격 증명은 읽기 전용일 수 있지만, 관리자 자격 증명을 제공하면 데이터 분류에서 높은 권한이 필요한 모든 데이터를 읽을 수 있습니다.  자격 증명은 데이터 분류 인스턴스에 저장됩니다.

CIFS 볼륨/파일 공유의 경우, Data Classification 스캔으로 인해 파일의 "마지막 액세스 시간"이 변경되지 않도록 하려면 사용자에게 Write Attributes 권한이 있어야 합니다. 가능하면 Active Directory에 구성된 사용자를 조직의 모든 파일에 대한 권한을 가진 상위 그룹에 포함시키는 것이 좋습니다.

.요구 사항
* 회사 사용자를 위해 Active Directory가 이미 설정되어 있어야 합니다.
* Active Directory에 대한 정보가 있어야 합니다.
+
** DNS 서버 IP 주소 또는 여러 IP 주소
+
또는

+
LDAP 서버 IP 주소 또는 여러 IP 주소

** 서버에 접속하기 위한 사용자 이름과 비밀번호
** 도메인 이름(Active Directory 이름)
** 보안 LDAP(LDAPS)를 사용하든 사용하지 않든
** LDAP 서버 포트(일반적으로 LDAP의 경우 389, 보안 LDAP의 경우 636)


* 다음 포트는 데이터 분류 인스턴스의 아웃바운드 통신을 위해 열려 있어야 합니다.
+
[cols="20,20,30,30"]
|===
| 규약 | 포트 | 목적지 | 목적 


| TCP 및 UDP | 389 | 액티브 디렉토리 | LDAP 


| TCP | 636 | 액티브 디렉토리 | SSL을 통한 LDAP 


| TCP | 3268 | 액티브 디렉토리 | 글로벌 카탈로그 


| TCP | 3269 | 액티브 디렉토리 | SSL을 통한 글로벌 카탈로그 
|===


.단계
. 데이터 분류에서 **구성**을 선택합니다.
. **Settings** 탭으로 전환하세요.
. Active Directory 제목에서 **추가**를 선택합니다.
. Active Directory에 연결 대화 상자에서 Active Directory 세부 정보를 입력한 다음 *Connect*를 선택합니다.
+
필요한 경우 *IP 추가*를 선택하여 여러 개의 IP 주소를 추가할 수 있습니다.

+
데이터 분류가 Active Directory에 통합되었으며, 구성 페이지에 새로운 섹션이 추가되었습니다.





[[manage-your-active-directory-integration]]
== Active Directory 통합 관리

Active Directory 통합 값을 수정해야 하는 경우 Data Classification에서 Active Directory 구성을 업데이트해야 합니다. Data Classification의 **구성** 메뉴로 돌아간 다음 설정 탭으로 이동하여 변경하십시오.

Active Directory 아래에 있는 **제거** 버튼을 선택하여 통합을 삭제할 수도 있습니다.
