---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, bugs, limitations, known issues, enhancements, fixes, data sense, cloud data sense, bluexp, bluexp classification' 
summary: BlueXP classification 의 새로운 기능을 알아보세요. 
---
= NetApp 데이터 분류의 새로운 기능
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp 데이터 분류의 새로운 기능을 알아보세요.



== 2025년 10월 6일



=== 버전 1.47

.BlueXP classification 는 이제 NetApp 데이터 분류입니다.
BlueXP classification NetApp 데이터 분류로 이름이 바뀌었습니다.  이름 변경 외에도 사용자 인터페이스가 향상되었습니다.

.BlueXP 는 이제 NetApp 콘솔입니다.
BlueXP 데이터 인프라 관리에서의 역할을 더 잘 반영하도록 이름이 바뀌고 재설계되었습니다.

NetApp 콘솔은 엔터프라이즈급 온프레미스 및 클라우드 환경 전반의 스토리지 및 데이터 서비스를 중앙에서 관리하여 실시간 통찰력, 더 빠른 워크플로, 간소화된 관리를 제공합니다.

변경된 사항에 대한 자세한 내용은 다음을 참조하세요. https://docs.netapp.com/us-en/console-relnotes/index.html["NetApp 콘솔 릴리스 노트"] .

.강화된 조사 경험
새로운 검색 필터, 값별 결과 수, 주요 결과를 요약한 실시간 통찰력, 사용자 정의 열과 슬라이드 아웃 세부 정보 창이 포함된 새로 고침된 결과 표를 통해 데이터를 더 빠르게 찾고 이해하세요.

자세한 내용은 다음을 참조하세요. link:https://docs.netapp.com/us-en/data-services-data-classification/task-investigate-data.html#view-file-metada["데이터 조사"] .

.새로운 거버넌스 및 규정 준수 대시보드
직관적인 위젯, 더욱 명확한 시각 자료, 향상된 로딩 성능을 통해 중요한 통찰력을 더 빠르게 얻으세요.  자세한 내용은 다음을 참조하세요.link:https://docs.netapp.com/us-en/data-services-data-classification//task-controlling-governance-data.html["귀하의 데이터에 대한 거버넌스 정보를 검토하세요"] 그리고link:https://docs.netapp.com/us-en/data-services-data-classification/task-controlling-private-data.html["귀하의 데이터에 대한 규정 준수 정보 보기"] .

.저장된 쿼리에 대한 정책(미리 보기)
이제 데이터 분류를 통해 조건부 작업으로 거버넌스를 자동화할 수 있습니다.  자동 삭제, 주기적 이메일 알림 등을 포함한 보존 규칙을 만들 수 있으며, 이 모든 것은 업데이트된 저장된 쿼리 페이지에서 관리할 수 있습니다.

자세한 내용은 다음을 참조하세요. link:https://docs.netapp.com/us-en/data-services-data-classification/task-using-policies.html["정책 생성"] .

.작업(미리 보기)
조사 페이지에서 직접 제어하세요. 파일을 개별적으로 또는 대량으로 삭제, 이동, 복사하거나 태그를 지정하여 효율적인 데이터 관리 및 수정이 가능합니다.

자세한 내용은 다음을 참조하세요. link:https://docs.netapp.com/us-en/data-services-data-classification/task-investigate-data.html#view-file-metada["데이터 조사"] .

.Google Cloud NetApp Volumes 지원
데이터 분류는 이제 Google Cloud NetApp Volumes 에서 스캐닝을 지원합니다.  NetApp 콘솔에서 Google Cloud NetApp Volumes 쉽게 추가하여 원활한 데이터 스캔 및 분류를 수행할 수 있습니다.



== 2025년 8월 11일



=== 버전 1.46

이 데이터 분류 릴리스에는 버그 수정과 다음 업데이트가 포함되어 있습니다.

.감사 페이지에서 향상된 스캔 이벤트 통찰력
감사 페이지는 이제 BlueXP classification 위한 스캔 이벤트에 대한 향상된 통찰력을 지원합니다.  이제 감사 페이지에 시스템 검사가 시작되는 시점, 시스템 상태, 문제가 표시됩니다.  공유 및 시스템 상태는 매핑 스캔에만 사용할 수 있습니다.

감사 페이지에 대한 자세한 내용은 다음을 참조하세요.link:https://docs.netapp.com/us-en/console-setup-admin/task-monitor-cm-operations.html["NetApp 콘솔 작업 모니터링"^] .

.RHEL 9.6 지원
이 릴리스에서는 다크 사이트 배포를 포함하여 BlueXP classification 의 수동 온프레미스 설치를 위한 Red Hat Enterprise Linux v9.6에 대한 지원이 추가되었습니다.

다음 운영 체제에서는 Podman 컨테이너 엔진을 사용해야 하며, BlueXP classification 버전 1.30 이상이 필요합니다: Red Hat Enterprise Linux 버전 8.8, 8.10, 9.0, 9.1, 9.2, 9.3, 9.4 및 9.5.



== 2025년 7월 14일



=== 버전 1.45

이 BlueXP classification 릴리스에는 리소스 활용도를 최적화하는 코드 변경 사항이 포함되어 있습니다.

.스캔을 위해 파일 공유를 추가하는 향상된 워크플로
파일 공유 그룹에 파일 공유를 추가하는 워크플로가 간소화되었습니다.  이 프로세스에서는 이제 인증 유형(Kerberos 또는 NTLM)에 따라 CIFS 프로토콜 지원을 구분합니다.

자세한 내용은 다음을 참조하세요. link:https://docs.netapp.com/us-en/data-services-data-classification/task-scanning-file-shares.html["파일 공유 스캔"] .

.향상된 파일 소유자 정보
이제 조사 탭에서 캡처된 파일의 파일 소유자에 대한 자세한 정보를 볼 수 있습니다.  조사 탭에서 파일의 메타데이터를 볼 때 파일 소유자를 찾은 다음 **세부 정보 보기**를 선택하여 사용자 이름, 이메일, SAM 계정 이름을 확인하세요.  이 사용자가 소유한 다른 항목도 볼 수 있습니다.  이 기능은 Active Directory가 있는 작업 환경에서만 사용할 수 있습니다.

자세한 내용은 다음을 참조하세요. link:https://docs.netapp.com/us-en/data-services-data-classification/task-investigate-data.html["귀하의 조직에 저장된 데이터를 조사하세요"] .



== 2025년 6월 10일



=== 버전 1.44

이 BlueXP classification 릴리스에는 다음이 포함됩니다.

.거버넌스 대시보드의 업데이트 시간이 개선되었습니다.
거버넌스 대시보드의 개별 구성 요소에 대한 업데이트 시간이 개선되었습니다.  다음 표는 각 구성 요소의 업데이트 빈도를 보여줍니다.

[cols="1,1"]
|===
| 요소 | 업데이트 시간 


| 데이터의 시대 | 24시간 


| 카테고리 | 24시간 


| 데이터 개요 | 5분 


| 중복 파일 | 2시간 


| 파일 유형 | 24시간 


| 비업무용 데이터 | 2시간 


| 공개 권한 | 24시간 


| 저장된 검색 | 2시간 


| 민감한 데이터 및 광범위한 권한 | 24시간 


| 데이터 크기 | 24시간 


| 오래된 데이터 | 2시간 


| 민감도 수준별 상위 데이터 저장소 | 2시간 
|===
마지막 업데이트 시간을 보고 중복 파일, 비업무 데이터, 저장된 검색, 오래된 데이터, 민감도 수준별 상위 데이터 저장소 구성 요소를 수동으로 업데이트할 수 있습니다. 거버넌스 대시보드에 대한 자세한 내용은 다음을 참조하세요.link:https://docs.netapp.com/us-en/data-services-data-classification/task-controlling-governance-data.html["조직에 저장된 데이터에 대한 거버넌스 세부 정보 보기"] .

.성능 및 보안 개선
BlueXP 분류의 성능, 메모리 소비, 보안을 개선하기 위해 개선 사항이 적용되었습니다.

.버그 수정
Redis가 업그레이드되어 BlueXP classification 의 안정성이 향상되었습니다.  BlueXP classification 이제 Elasticsearch를 사용하여 스캔 중 파일 수 보고의 정확도를 향상시킵니다.



== 2025년 5월 12일



=== 버전 1.43

이 데이터 분류 릴리스에는 다음이 포함됩니다.

.분류 스캔 우선 순위 지정
데이터 분류는 매핑 전용 스캔 외에도 맵 및 분류 스캔의 우선순위를 지정하는 기능을 지원하여 어떤 스캔을 먼저 완료할지 선택할 수 있습니다.  Map & Classify 스캔의 우선순위 지정은 스캔이 시작되기 전과 시작 중 지원됩니다.  검사가 진행되는 동안 검사의 우선순위를 지정하는 경우 매핑 검사와 분류 검사가 모두 우선순위가 지정됩니다.

자세한 내용은 다음을 참조하세요. link:https://docs.netapp.com/us-en/data-services-data-classification/task-managing-repo-scanning.html#prioritize-scans["스캔 우선 순위 지정"] .

.캐나다 개인 식별 정보(PII) 데이터 범주 지원
데이터 분류 스캔은 캐나다 PII 데이터 범주를 식별합니다.  이러한 범주에는 모든 캐나다 주와 지역의 은행 정보, 여권 번호, 사회보장번호, 운전면허증 번호, 건강카드 번호가 포함됩니다.

자세한 내용은 다음을 참조하세요. link:https://docs.netapp.com/us-en/data-services-data-classification/reference-private-data-categories.html#types-of-personal-data["개인 데이터 범주"] .

.사용자 정의 분류(미리 보기)
데이터 분류는 Map & Classify 스캔에 대한 사용자 정의 분류를 지원합니다.  사용자 정의 분류를 사용하면 정규 표현식을 사용하여 조직에 맞는 데이터를 캡처하도록 데이터 분류 검사를 맞춤화할 수 있습니다.  이 기능은 현재 미리보기 단계에 있습니다.

자세한 내용은 다음을 참조하세요. link:https://docs.netapp.com/us-en/data-services-data-classification/task-custom-classification.html["사용자 정의 분류 추가"] .

.저장된 검색 탭
**정책** 탭의 이름이 변경되었습니다.link:https://docs.netapp.com/us-en/data-services-data-classification/task-using-policies.html["**저장된 검색**"] . 기능은 변경되지 않았습니다.

.감사 페이지로 스캔 이벤트 보내기
데이터 분류는 분류 이벤트(스캔이 시작될 때와 종료될 때)를 전송하는 것을 지원합니다.link:https://docs.netapp.com/us-en/console-setup-admin/task-monitor-cm-operations.html#audit-user-activity-from-the-bluexp-timeline["NetApp Consle Audit 페이지"^] .

.보안 업데이트
* Keras 패키지가 업데이트되어 취약점(BDSA-2025-0107 및 BDSA-2025-1984)이 완화되었습니다.
* Docker 컨테이너 구성이 업데이트되었습니다.  컨테이너는 더 이상 원시 네트워크 패킷을 제작하기 위해 호스트의 네트워크 인터페이스에 액세스할 수 없습니다.  불필요한 접근을 줄임으로써 업데이트를 통해 잠재적인 보안 위험이 완화됩니다.


.성능 향상
RAM 사용량을 줄이고 데이터 분류의 전반적인 성능을 개선하기 위해 코드 개선이 구현되었습니다.

.버그 수정
StorageGRID 검사가 실패하고, 조사 페이지 필터 옵션이 로드되지 않으며, 대용량 평가의 경우 데이터 검색 평가가 다운로드되지 않는 버그가 수정되었습니다.



== 2025년 4월 14일



=== 버전 1.42

이 BlueXP classification 릴리스에는 다음이 포함됩니다.

.작업 환경을 위한 대량 스캐닝
BlueXP classification 작업 환경에서 대량 작업을 지원합니다.  작업 환경의 볼륨 전반에 걸쳐 매핑 스캔을 활성화하거나, 맵 및 분류 스캔을 활성화하거나, 스캔을 비활성화하거나, 사용자 정의 구성을 만들 수 있습니다.  개별 볼륨에 대한 선택을 하면 대량 선택이 무시됩니다.  대량 작업을 수행하려면 **구성** 페이지로 이동하여 선택하세요.

.조사 보고서를 로컬로 다운로드하세요
BlueXP classification 데이터 조사 보고서를 로컬로 다운로드하여 브라우저에서 볼 수 있는 기능을 지원합니다.  로컬 옵션을 선택하는 경우 데이터 조사는 CSV 형식으로만 가능하며, 데이터의 처음 10,000개 행만 표시됩니다.

자세한 내용은 다음을 참조하세요. link:https://docs.netapp.com/us-en/data-services-data-classification/task-investigate-data.html#create-the-data-investigation-report["BlueXP classification 사용하여 조직에 저장된 데이터를 조사하세요"] .



== 2025년 3월 10일



=== 버전 1.41

이 BlueXP classification 릴리스에는 일반적인 개선 사항과 버그 수정이 포함되어 있습니다.  여기에는 다음이 포함됩니다.

.스캔 상태
BlueXP classification 볼륨의 _초기_ 매핑 및 분류 스캔의 실시간 진행 상황을 추적합니다.  별도의 진행 막대는 매핑 및 분류 스캔을 추적하여 스캔된 전체 파일의 백분율을 나타냅니다.  진행률 표시줄 위에 마우스를 올려 놓으면 검사된 파일 수와 전체 파일을 볼 수 있습니다.  검사 상태를 추적하면 검사 진행 상황에 대한 심층적인 통찰력이 제공되어 검사를 보다 효과적으로 계획하고 리소스 할당을 이해하는 데 도움이 됩니다.

스캔 상태를 보려면 BlueXP classification 에서 **구성**으로 이동한 다음 **작업 환경 구성**을 선택하세요.  각 권의 진행 상황은 줄에 따라 표시됩니다.



== 2025년 2월 19일



=== 버전 1.40

이 BlueXP classification 릴리스에는 다음과 같은 업데이트가 포함되어 있습니다.

.RHEL 9.5 지원
이 릴리스에서는 이전에 지원되었던 버전 외에도 Red Hat Enterprise Linux v9.5에 대한 지원이 제공됩니다.  이는 다크 사이트 배포를 포함하여 BlueXP classification 의 모든 수동 온프레미스 설치에 적용됩니다.

다음 운영 체제에서는 Podman 컨테이너 엔진을 사용해야 하며, BlueXP classification 버전 1.30 이상이 필요합니다: Red Hat Enterprise Linux 버전 8.8, 8.10, 9.0, 9.1, 9.2, 9.3, 9.4 및 9.5.

.매핑 전용 스캔 우선 순위 지정
매핑 전용 스캔을 수행할 때 가장 중요한 스캔의 우선순위를 지정할 수 있습니다.  이 기능은 작업 환경이 여러 개이고 우선 순위가 높은 스캔을 먼저 완료하려는 경우에 유용합니다.

기본적으로 스캔은 시작된 순서에 따라 대기열에 추가됩니다.  검사의 우선순위를 지정하는 기능을 사용하면 검사를 대기열의 앞으로 옮길 수 있습니다.  여러 스캔에 우선순위를 지정할 수 있습니다.  우선순위는 선입선출 순서로 지정됩니다. 즉, 우선순위를 지정한 첫 번째 스캔이 대기열의 앞으로 이동하고, 두 번째로 우선순위를 지정한 스캔이 대기열의 두 번째가 되는 식입니다.

우선권은 한 번만 부여됩니다.  매핑 데이터의 자동 재스캔은 기본 순서대로 수행됩니다.

우선순위는 다음으로 제한됩니다.link:https://docs.netapp.com/us-en/data-services-data-classification/concept-classification.html["매핑 전용 스캔"^] ; 지도 및 분류 스캔에는 사용할 수 없습니다.

자세한 내용은 다음을 참조하세요. link:https://docs.netapp.com/us-en/data-services-data-classification/task-managing-repo-scanning.html#prioritize-scans["스캔 우선 순위 지정"^] .

.모든 스캔을 다시 시도하세요
BlueXP classification 실패한 모든 스캔을 일괄적으로 다시 시도하는 기능을 지원합니다.

**모두 다시 시도** 기능을 사용하면 일괄 작업으로 스캔을 다시 시도할 수 있습니다.  네트워크 중단과 같은 일시적인 문제로 인해 분류 스캔이 실패하는 경우, 개별적으로 다시 시도하는 대신 하나의 버튼으로 모든 스캔을 동시에 다시 시도할 수 있습니다.  필요한 만큼 스캔을 다시 시도할 수 있습니다.

모든 스캔을 다시 시도하려면:

. BlueXP classification 메뉴에서 *구성*을 선택합니다.
. 실패한 모든 검사를 다시 시도하려면 *모든 검사 다시 시도*를 선택하세요.


.향상된 분류 모델 정확도
머신 러닝 모델의 정확도link:https://docs.netapp.com/us-en/data-services-data-classification/reference-private-data-categories.html#types-of-sensitive-personal-datapredefined-categories["미리 정의된 카테고리"] 11% 개선되었습니다.



== 2025년 1월 22일



=== 버전 1.39

이 BlueXP classification 릴리스에서는 데이터 조사 보고서의 내보내기 프로세스가 업데이트되었습니다.  이 내보내기 업데이트는 데이터에 대한 추가 분석을 수행하거나, 데이터에 대한 추가 시각화를 생성하거나, 데이터 조사 결과를 다른 사람들과 공유하는 데 유용합니다.

이전에는 데이터 조사 보고서 내보내기가 10,000개 행으로 제한되었습니다.  이번 릴리스에서는 이러한 제한이 없어져 모든 데이터를 내보낼 수 있게 되었습니다.  이 변경을 통해 데이터 조사 보고서에서 더 많은 데이터를 내보낼 수 있으므로 데이터 분석에 있어 더 많은 유연성이 제공됩니다.

작업 환경, 볼륨, 대상 폴더, JSON 또는 CSV 형식을 선택할 수 있습니다.  내보낸 파일 이름에는 데이터가 언제 내보내졌는지 식별하는 데 도움이 되는 타임스탬프가 포함됩니다.

지원되는 작업 환경은 다음과 같습니다.

* Cloud Volumes ONTAP
* ONTAP 용 FSx
* ONTAP
* 그룹 공유


데이터 조사 보고서에서 데이터를 내보내는 데는 다음과 같은 제한이 있습니다.

* 다운로드 가능한 최대 레코드 수는 유형(파일, 디렉토리, 테이블)당 5억 개입니다.
* 100만 개의 레코드를 내보내는 데는 약 35분이 걸릴 것으로 예상됩니다.


데이터 조사 및 보고서에 대한 자세한 내용은 다음을 참조하세요. https://docs.netapp.com/us-en/data-services-data-classification/task-investigate-data.html["귀하의 조직에 저장된 데이터를 조사하세요"] .



== 2024년 12월 16일



=== 버전 1.38

이 BlueXP classification 릴리스에는 일반적인 개선 사항과 버그 수정이 포함되어 있습니다.



== 2024년 11월 4일



=== 버전 1.37

이 BlueXP classification 릴리스에는 다음과 같은 업데이트가 포함되어 있습니다.

.RHEL 8.10 지원
이 릴리스에서는 이전에 지원되었던 버전 외에도 Red Hat Enterprise Linux v8.10에 대한 지원이 제공됩니다.  이는 다크 사이트 배포를 포함하여 BlueXP classification 의 모든 수동 온프레미스 설치에 적용됩니다.

다음 운영 체제에서는 Podman 컨테이너 엔진을 사용해야 하며, BlueXP classification 버전 1.30 이상이 필요합니다: Red Hat Enterprise Linux 버전 8.8, 8.10, 9.0, 9.1, 9.2, 9.3 및 9.4.

자세히 알아보세요 https://docs.netapp.com/us-en/data-services-data-classification/concept-classification.html["BlueXP classification"] .

.NFS v4.1 지원
이 릴리스에서는 이전에 지원되었던 버전 외에도 NFS v4.1에 대한 지원이 제공됩니다.

자세히 알아보세요 https://docs.netapp.com/us-en/data-services-data-classification/concept-classification.html["BlueXP classification"] .



== 2024년 10월 10일



=== 버전 1.36

.RHEL 9.4 지원
이 릴리스에서는 이전에 지원되었던 버전 외에도 Red Hat Enterprise Linux v9.4에 대한 지원이 제공됩니다.  이는 다크 사이트 배포를 포함하여 BlueXP classification 의 모든 수동 온프레미스 설치에 적용됩니다.

다음 운영 체제에서는 Podman 컨테이너 엔진을 사용해야 하며, BlueXP classification 버전 1.30 이상이 필요합니다: Red Hat Enterprise Linux 버전 8.8, 9.0, 9.1, 9.2, 9.3 및 9.4.

자세히 알아보세요 https://docs.netapp.com/us-en/data-services-data-classification/task-deploy-overview.html["BlueXP classification 배포 개요"] .

.향상된 스캔 성능
이 릴리스에서는 향상된 스캔 성능이 제공됩니다.



== 2024년 9월 2일



=== 버전 1.35

.StorageGRID 데이터 스캔
BlueXP classification StorageGRID 에서 데이터 스캐닝을 지원합니다.

자세한 내용은 다음을 참조하세요.link:task-scanning-storagegrid.html["StorageGRID 데이터 스캔"] .



== 2024년 8월 5일



=== 버전 1.34

이 BlueXP classification 릴리스에는 다음 업데이트가 포함되어 있습니다.

.CentOS에서 Ubuntu로 변경
BlueXP classification Microsoft Azure 및 Google Cloud Platform(GCP)용 Linux 운영 체제를 CentOS 7.9에서 Ubuntu 22.04로 업데이트했습니다.

배포 세부 사항은 다음을 참조하세요. https://docs.netapp.com/us-en/data-services-data-classification/task-deploy-compliance-onprem.html#prepare-the-linux-host-system["인터넷 접속이 가능한 Linux 호스트에 설치하고 Linux 호스트 시스템을 준비합니다."] .



== 2024년 7월 1일



=== 버전 1.33

.Ubuntu 지원
이 릴리스는 Ubuntu 24.04 Linux 플랫폼을 지원합니다.

.매핑 스캔은 메타데이터를 수집합니다.
다음 메타데이터는 매핑 스캔 중에 파일에서 추출되어 거버넌스, 규정 준수 및 조사 대시보드에 표시됩니다.

* 작업 환경
* 작업 환경 유형
* 저장 저장소
* 파일 유형
* 사용된 용량
* 파일 수
* 파일 크기
* 파일 생성
* 파일 마지막 접근
* 파일이 마지막으로 수정되었습니다
* 파일 발견 시간
* 권한 추출


.대시보드의 추가 데이터
이 릴리스에서는 매핑 스캔 중에 거버넌스, 규정 준수 및 조사 대시보드에 표시되는 데이터가 업데이트되었습니다.

자세한 내용은 다음을 참조하십시오. link:https://docs.netapp.com/us-en/data-services-data-classification/concept-classification.html["매핑 스캔과 분류 스캔의 차이점은 무엇입니까?"] .



== 2024년 6월 5일



=== 버전 1.32

.구성 페이지의 새 매핑 상태 열
이 릴리스에서는 이제 구성 페이지에 새로운 매핑 상태 열이 표시됩니다.  새로운 열은 매핑이 실행 중인지, 대기 중인지, 일시 중지된 상태인지 등을 식별하는 데 도움이 됩니다.

상태에 대한 설명은 다음을 참조하세요. https://docs.netapp.com/us-en/data-services-data-classification/task-managing-repo-scanning.html["스캔 설정 변경"] .



== 2024년 5월 15일



=== 버전 1.31

.분류는 BlueXP 의 핵심 서비스로 제공됩니다.
BlueXP classification 이제 커넥터당 최대 500TiB의 스캔 데이터에 대해 추가 비용 없이 BlueXP 의 핵심 기능으로 제공됩니다.  분류 라이센스나 유료 구독이 필요하지 않습니다.  이 새로운 버전에서는 BlueXP classification 기능을 NetApp 스토리지 시스템 스캐닝에 집중하므로 일부 기존 기능은 이전에 라이선스 비용을 지불한 고객만 사용할 수 있습니다.  유료 계약이 종료되면 해당 레거시 기능의 사용은 만료됩니다.


NOTE: 데이터 분류는 스캔할 수 있는 데이터 양에 제한을 두지 않습니다. 각 콘솔 에이전트는 500TiB의 데이터를 스캔하고 표시하는 것을 지원합니다. 500TiB 이상의 데이터를 스캔하려면link:https://docs.netapp.com/us-en/console-setup-admin/concept-connectors.html#connector-installation["다른 콘솔 에이전트를 설치하세요"^] 그 다음에link:https://docs.netapp.com/us-en/data-services-data-classification/task-deploy-overview.html["다른 데이터 분류 인스턴스 배포"] . + 콘솔 UI는 단일 커넥터의 데이터를 표시합니다. 여러 콘솔 에이전트의 데이터를 보는 방법에 대한 팁은 다음을 참조하세요.link:https://docs.netapp.com/us-en/console-setup-admin/task-manage-multiple-connectors.html#switch-between-connectors["여러 콘솔 에이전트와 함께 작업"^] .



== 2024년 4월 1일



=== 버전 1.30

.RHEL v8.8 및 v9.3 BlueXP classification 에 대한 지원이 추가되었습니다.
이 릴리스에서는 Docker 엔진이 아닌 Podman이 필요한 기존 지원 버전 9.x 외에도 Red Hat Enterprise Linux v8.8 및 v9.3에 대한 지원이 제공됩니다.  이는 BlueXP classification 의 모든 수동 온프레미스 설치에 적용됩니다.

다음 운영 체제에서는 Podman 컨테이너 엔진을 사용해야 하며, BlueXP classification 버전 1.30 이상이 필요합니다: Red Hat Enterprise Linux 버전 8.8, 9.0, 9.1, 9.2 및 9.3.

자세히 알아보세요 https://docs.netapp.com/us-en/data-services-data-classification/task-deploy-overview.html["BlueXP classification 배포 개요"] .

온프레미스에 있는 RHEL 8 또는 9 호스트에 커넥터를 설치하는 경우 BlueXP classification 지원됩니다. RHEL 8 또는 9 호스트가 AWS, Azure 또는 Google Cloud에 있는 경우 지원되지 않습니다.

.감사 로그 수집 활성화 옵션이 제거되었습니다.
감사 로그 수집을 활성화하는 옵션이 비활성화되었습니다.

.스캔 속도가 향상되었습니다
보조 스캐너 노드의 스캔 성능이 개선되었습니다.  스캔에 대한 처리 능력이 더 필요하면 스캐너 노드를 추가할 수 있습니다. 자세한 내용은 다음을 참조하세요. https://docs.netapp.com/us-en/data-services-data-classification/task-deploy-compliance-onprem.html["인터넷 접속이 가능한 호스트에 BlueXP classification 설치합니다."] .

.자동 업그레이드
인터넷 접속이 가능한 시스템에 BlueXP classification 배포한 경우 시스템이 자동으로 업그레이드됩니다.  이전에는 마지막 사용자 활동 이후 특정 시간이 경과한 후에 업그레이드가 이루어졌습니다.  이 릴리스에서는 현지 시간이 오전 1시에서 오전 5시 사이인 경우 BlueXP classification 자동으로 업그레이드됩니다.  현지 시간이 이 시간대를 벗어나면 마지막 사용자 활동 이후 특정 시간이 경과한 후에 업그레이드가 수행됩니다. 자세한 내용은 다음을 참조하세요. https://docs.netapp.com/us-en/data-services-data-classification/task-deploy-compliance-onprem.html["인터넷 접속이 가능한 Linux 호스트에 설치"] .

인터넷 접속 없이 BlueXP classification 배포한 경우 수동으로 업그레이드해야 합니다. 자세한 내용은 다음을 참조하세요. https://docs.netapp.com/us-en/data-services-data-classification/task-deploy-compliance-dark-site.html["인터넷 접속이 없는 Linux 호스트에 BlueXP classification 설치"] .



== 2024년 3월 4일



=== 버전 1.29

.이제 특정 데이터 소스 디렉토리에 있는 스캐닝 데이터를 제외할 수 있습니다.
BlueXP classification 특정 데이터 소스 디렉토리에 있는 스캐닝 데이터를 제외하려면 BlueXP classification 에서 처리하는 구성 파일에 이러한 디렉토리 이름을 추가할 수 있습니다.  이 기능을 사용하면 불필요한 디렉토리를 스캔하지 않아도 되고, 잘못된 개인 데이터 결과가 반환되는 것을 방지할 수 있습니다.

https://docs.netapp.com/us-en/data-services-data-classification/task-exclude-scan-paths.html["자세히 알아보기"] .

.초대형 인스턴스 지원이 이제 인증되었습니다.
2억 5천만 개가 넘는 파일을 검사하기 위해 BlueXP classification 필요한 경우 클라우드 배포 또는 온프레미스 설치에서 Extra Large 인스턴스를 사용할 수 있습니다.  이러한 유형의 시스템은 최대 5억 개의 파일을 검사할 수 있습니다.

https://docs.netapp.com/us-en/data-services-data-classification/concept-classification.html#the-data-classification-instance["자세히 알아보기"] .



== 2024년 1월 10일



=== 버전 1.27

.조사 페이지 결과에는 총 항목 수 외에도 총 크기가 표시됩니다.
조사 페이지에서 필터링된 결과에는 총 파일 수 외에도 항목의 총 크기가 표시됩니다.  이 기능은 파일을 이동하거나, 파일을 삭제하는 등의 작업에 도움이 될 수 있습니다.

.추가 그룹 ID를 "조직에 공개"로 구성합니다.
그룹에 원래 해당 권한이 설정되지 않은 경우, 이제 BlueXP classification 에서 직접 NFS의 그룹 ID를 "조직에 개방됨"으로 간주하도록 구성할 수 있습니다.  이러한 그룹 ID가 첨부된 모든 파일과 폴더는 조사 세부 정보 페이지에서 "조직에 공개됨"으로 표시됩니다. 방법을 확인하세요link:https://docs.netapp.com/us-en/data-services-data-classification/task-add-group-id-as-open.html["추가 그룹 ID를 "조직에 공개"로 추가합니다."] .



== 2023년 12월 14일



=== 버전 1.26.6

이번 릴리스에는 몇 가지 사소한 개선 사항이 포함되었습니다.

이 릴리스에서는 다음 옵션도 제거되었습니다.

* 감사 로그 수집을 활성화하는 옵션이 비활성화되었습니다.
* 디렉토리 조사 중에 디렉토리별 개인 식별 정보(PII) 데이터 수를 계산하는 옵션을 사용할 수 없습니다. link:task-investigate-data.html["귀하의 조직에 저장된 데이터를 조사하세요"] .
* Azure Information Protection(AIP) 레이블을 사용하여 데이터를 통합하는 옵션이 비활성화되었습니다.




== 2023년 11월 6일



=== 버전 1.26.3

이 릴리스에서는 다음 문제가 해결되었습니다.

* 대시보드에서 시스템이 스캔한 파일 수를 표시할 때 발생하는 불일치를 해결했습니다.
* 이름과 메타데이터에 특수 문자가 포함된 파일과 디렉토리를 처리하고 보고하여 스캐닝 동작을 개선했습니다.




== 2023년 10월 4일



=== 버전 1.26

.RHEL 버전 9에서 BlueXP classification 의 온프레미스 설치 지원
Red Hat Enterprise Linux 버전 8과 9는 BlueXP classification 설치에 필요한 Docker 엔진을 지원하지 않습니다. 이제 Podman 버전 4 이상을 컨테이너 인프라로 사용하여 RHEL 9.0, 9.1 및 9.2에서 BlueXP classification 설치를 지원합니다. 사용자 환경에서 최신 버전의 RHEL을 사용해야 하는 경우 이제 Podman을 사용할 때 BlueXP classification (버전 1.26 이상)를 설치할 수 있습니다.

현재 RHEL 9.x를 사용할 경우 다크 사이트 설치나 분산 스캐닝 환경(마스터 및 원격 스캐너 노드 사용)은 지원되지 않습니다.



== 2023년 9월 5일



=== 버전 1.25

.소규모 및 중규모 배포는 일시적으로 사용할 수 없습니다.
AWS에서 BlueXP classification 인스턴스를 배포할 때 *배포 > 구성*을 선택하고 소규모 또는 중규모 인스턴스를 선택하는 옵션은 현재 사용할 수 없습니다. *배포 > 배포*를 선택하면 대용량 인스턴스 크기를 사용하여 인스턴스를 배포할 수 있습니다.

.조사 결과 페이지에서 최대 100,000개 항목에 태그를 적용합니다.
과거에는 조사 결과 페이지에서 한 번에 하나의 페이지(20개 항목)에만 태그를 적용할 수 있었습니다. 이제 조사 결과 페이지에서 *모든* 항목을 선택하고 모든 항목에 태그를 적용할 수 있습니다. 한 번에 최대 100,000개 항목까지 적용할 수 있습니다.

.최소 1MB의 파일 크기를 갖는 중복 파일을 식별합니다.
BlueXP classification 파일 크기가 50MB 이상인 경우에만 중복 파일을 식별하는 데 사용됩니다. 이제 1MB로 시작하는 중복 파일을 식별할 수 있습니다. 조사 페이지 필터인 "파일 크기"와 "중복"을 사용하여 사용자 환경에서 특정 크기의 어떤 파일이 중복되었는지 확인할 수 있습니다.



== 2023년 7월 17일



=== 버전 1.24

.BlueXP classification 를 통해 두 가지 새로운 유형의 독일 개인 데이터가 식별되었습니다.
BlueXP classification 다음 유형의 데이터를 포함하는 파일을 식별하고 분류할 수 있습니다.

* 독일 ID(Personalausweisnummer)
* 독일 사회 보장 번호(Sozialversicherungsnummer)


link:https://docs.netapp.com/us-en/data-services-data-classification/reference-private-data-categories.html#types-of-personal-data["BlueXP classification 귀하의 데이터에서 식별할 수 있는 모든 유형의 개인 데이터를 확인하세요."] .

.BlueXP classification 제한 모드와 비공개 모드에서 완벽하게 지원됩니다.
이제 BlueXP classification 인터넷 접속이 불가능한 사이트(개인 모드)와 아웃바운드 인터넷 접속이 제한된 사이트(제한 모드)에서도 완벽하게 지원됩니다. link:https://docs.netapp.com/us-en/console-setup-admin/concept-modes.html["커넥터용 BlueXP 배포 모드에 대해 자세히 알아보세요."^] .

.BlueXP classification 의 개인 모드 설치를 업그레이드할 때 버전을 건너뛸 수 있는 기능
이제 순차적이지 않더라도 최신 버전의 BlueXP classification 로 업그레이드할 수 있습니다.  즉, BlueXP classification 한 번에 한 버전씩 업그레이드해야 하는 현재 제한은 더 이상 필요하지 않습니다.  이 기능은 1.24 버전부터 적용됩니다.

.BlueXP classification API를 이제 사용할 수 있습니다.
BlueXP classification API를 사용하면 스캔 중인 데이터에 대한 작업을 수행하고, 쿼리를 만들고, 정보를 내보낼 수 있습니다.  대화형 문서는 Swagger를 사용하여 사용할 수 있습니다.  문서는 조사, 규정 준수, 거버넌스, 구성을 포함한 여러 범주로 구분됩니다.  각 카테고리는 BlueXP classification UI의 탭을 참조합니다.

link:https://docs.netapp.com/us-en/data-services-data-classification/api-classification.html["BlueXP classification API에 대해 자세히 알아보세요"] .



== 2023년 6월 6일



=== 버전 1.23

.이제 데이터 주체 이름을 검색할 때 일본어가 지원됩니다.
이제 데이터 주체 접근 요청(DSAR)에 대한 응답으로 주체의 이름을 검색할 때 일본어 이름을 입력할 수 있습니다.  생성할 수 있습니다link:https://docs.netapp.com/us-en/data-services-data-classification/task-generating-compliance-reports.html["데이터 주체 접근 요청 보고서"] 그 결과 정보를 사용하여.  일본어 이름도 입력할 수 있습니다.link:https://docs.netapp.com/us-en/data-services-data-classification/task-investigate-data.html["데이터 조사 페이지의 "데이터 주체" 필터"] 주제의 이름이 포함된 파일을 식별합니다.

.Ubuntu는 이제 BlueXP classification 설치할 수 있는 지원되는 Linux 배포판입니다.
Ubuntu 22.04는 BlueXP classification 에 지원되는 운영 체제로 인증되었습니다.  설치 프로그램의 버전 1.23을 사용하면 네트워크의 Ubuntu Linux 호스트나 클라우드의 Linux 호스트에 BlueXP classification 설치할 수 있습니다. https://docs.netapp.com/us-en/data-services-data-classification/task-deploy-compliance-onprem.html["Ubuntu가 설치된 호스트에 BlueXP classification 설치하는 방법을 알아보세요."] .

.Red Hat Enterprise Linux 8.6 및 8.7은 더 이상 새로운 BlueXP classification 설치에서 지원되지 않습니다.
Docker는 Red Hat이 더 이상 필수 조건이므로 이러한 버전은 새로운 배포에서는 지원되지 않습니다.  RHEL 8.6 또는 8.7에서 실행되는 기존 BlueXP classification 머신이 있는 경우 NetApp 해당 구성을 계속 지원합니다.

.BlueXP classification ONTAP 시스템에서 FPolicy 이벤트를 수신하기 위한 FPolicy 수집기로 구성될 수 있습니다.
작업 환경의 볼륨에서 감지된 파일 액세스 이벤트에 대해 BlueXP classification 시스템에서 파일 액세스 감사 로그를 수집하도록 설정할 수 있습니다.  BlueXP classification 다음과 같은 유형의 FPolicy 이벤트와 파일에 대한 작업을 수행한 사용자를 캡처할 수 있습니다: 만들기, 읽기, 쓰기, 삭제, 이름 바꾸기, 소유자/권한 변경, SACL/DACL 변경.

.이제 다크 사이트에서 Data Sense BYOL 라이선스가 지원됩니다.
이제 다크 사이트에서 Data Sense BYOL 라이선스를 BlueXP digital wallet 에 업로드하여 라이선스가 부족해질 때 알림을 받을 수 있습니다.



== 2023년 4월 3일



=== 버전 1.22

.새로운 데이터 발견 평가 보고서
데이터 검색 평가 보고서는 스캔한 환경에 대한 높은 수준의 분석을 제공하여 시스템 결과를 강조하고 문제가 있는 영역과 잠재적인 수정 단계를 보여줍니다.  이 보고서의 목적은 데이터 세트의 데이터 거버넌스 문제, 데이터 보안 노출, 데이터 규정 준수 격차에 대한 인식을 높이는 것입니다. https://docs.netapp.com/us-en/data-services-data-classification/task-controlling-governance-data.html["데이터 발견 평가 보고서를 생성하고 사용하는 방법을 알아보세요."] .

.클라우드의 소규모 인스턴스에 BlueXP classification 배포하는 기능
AWS 환경에서 BlueXP Connector를 통해 BlueXP classification 배포할 때 이제 기본 인스턴스에서 사용할 수 있는 것보다 더 작은 두 개의 인스턴스 유형 중에서 선택할 수 있습니다.  소규모 환경을 스캔하는 경우 클라우드 비용을 절감하는 데 도움이 될 수 있습니다.  하지만 작은 인스턴스를 사용할 때는 몇 가지 제한이 있습니다. https://docs.netapp.com/us-en/data-services-data-classification/concept-classification.html["사용 가능한 인스턴스 유형 및 제한 사항을 확인하세요."] .

.이제 BlueXP classification 설치 전에 Linux 시스템을 검증하기 위한 독립 실행형 스크립트를 사용할 수 있습니다.
BlueXP classification 설치를 실행하지 않고도 Linux 시스템이 모든 필수 구성 요소를 충족하는지 확인하려면 필수 구성 요소만 테스트하는 별도의 스크립트를 다운로드할 수 있습니다. https://docs.netapp.com/us-en/data-services-data-classification/task-test-linux-system.html["Linux 호스트가 BlueXP classification 설치할 준비가 되었는지 확인하는 방법을 알아보세요."] .



== 2023년 3월 7일



=== 버전 1.21

.BlueXP classification UI에서 사용자 정의 범주를 추가하는 새로운 기능
이제 BlueXP classification 통해 사용자 정의 범주를 추가할 수 있으므로 BlueXP classification 통해 해당 범주에 맞는 파일을 식별할 수 있습니다.  BlueXP classification 에는 많은 것이 있습니다 https://docs.netapp.com/us-en/data-services-data-classification/reference-private-data-categories.html["미리 정의된 카테고리"] 따라서 이 기능을 사용하면 사용자 정의 범주를 추가하여 조직에 고유한 정보가 데이터에서 어디에 있는지 식별할 수 있습니다.

.이제 BlueXP classification UI에서 사용자 정의 키워드를 추가할 수 있습니다.
BlueXP classification 향후 스캔에서 BlueXP classification 식별할 수 있는 사용자 정의 키워드를 추가하는 기능을 갖추고 있습니다.  하지만 키워드를 추가하려면 BlueXP classification Linux 호스트에 로그인하고 명령줄 인터페이스를 사용해야 합니다.  이번 릴리스에서는 BlueXP classification UI에 사용자 정의 키워드를 추가하는 기능이 추가되어 키워드를 매우 쉽게 추가하고 편집할 수 있습니다.

."마지막 액세스 시간"이 변경될 때 BlueXP classification 가 파일을 스캔하지 않도록 하는 기능
기본적으로 BlueXP classification 적절한 "쓰기" 권한이 없으면 시스템은 볼륨의 파일을 검사하지 않습니다. BlueXP classification "마지막 액세스 시간"을 원래 타임스탬프로 되돌릴 수 없기 때문입니다.  하지만 파일의 마지막 액세스 시간이 원래 시간으로 재설정되는 것이 문제가 되지 않는다면 구성 페이지에서 이 동작을 재정의하여 BlueXP classification 권한에 관계없이 볼륨을 검사하도록 할 수 있습니다.

이 기능과 함께 "스캔 분석 이벤트"라는 새 필터가 추가되어 BlueXP classification 에서 마지막 액세스 시간을 되돌릴 수 없어 분류되지 않은 파일이나 BlueXP classification 마지막 액세스 시간을 되돌릴 수 없어도 분류된 파일을 볼 수 있습니다.

https://docs.netapp.com/us-en/data-services-data-classification/reference-collected-metadata.html[""마지막 액세스 시간 타임스탬프" 및 BlueXP classification 에 필요한 권한에 대해 자세히 알아보세요."] .

.BlueXP classification 통해 3가지 새로운 유형의 개인 데이터가 식별되었습니다.
BlueXP classification 다음 유형의 데이터를 포함하는 파일을 식별하고 분류할 수 있습니다.

* 보츠와나 신분증(오망) 번호
* 보츠와나 여권 번호
* 싱가포르 국민등록 신분증(NRIC)


https://docs.netapp.com/us-en/data-services-data-classification/reference-private-data-categories.html["BlueXP classification 귀하의 데이터에서 식별할 수 있는 모든 유형의 개인 데이터를 확인하세요."] .

.디렉토리에 대한 업데이트된 기능
* 데이터 조사 보고서의 "간단한 CSV 보고서" 옵션에 이제 디렉토리의 정보가 포함됩니다.
* "마지막 액세스" 시간 필터는 이제 파일과 디렉토리 모두에 대한 마지막 액세스 시간을 표시합니다.


.설치 개선 사항
* 인터넷 접속이 불가능한 사이트(다크 사이트)를 위한 BlueXP classification 설치 프로그램은 이제 성공적인 설치를 위해 시스템 및 네트워킹 요구 사항이 제대로 갖춰져 있는지 사전 검사를 수행합니다.
* 설치 감사 로그 파일이 이제 저장되었습니다. `/ops/netapp/install_logs` .




== 2023년 2월 5일



=== 버전 1.20

.모든 이메일 주소로 정책 기반 알림 이메일을 보낼 수 있는 기능
이전 버전의 BlueXP classification 에서는 특정 중요 정책에 대한 결과가 반환되면 계정의 BlueXP 사용자에게 이메일 알림을 보낼 수 있었습니다.  이 기능을 사용하면 온라인 상태가 아닐 때 데이터를 보호하기 위한 알림을 받을 수 있습니다.  이제 BlueXP 계정에 없는 다른 사용자(최대 20개 이메일 주소)에게도 정책에서 이메일 알림을 보낼 수 있습니다.

https://docs.netapp.com/us-en/data-services-data-classification/task-using-policies.html["정책 결과에 따라 이메일 알림을 보내는 방법에 대해 자세히 알아보세요."] .

.이제 BlueXP classification UI에서 개인 패턴을 추가할 수 있습니다.
BlueXP classification BlueXP classification 스캔에서 식별할 수 있는 맞춤형 "개인 데이터"를 추가하는 기능을 갖추고 있습니다.  하지만 사용자 정의 패턴을 추가하려면 BlueXP classification Linux 호스트에 로그인하고 명령줄을 사용해야 했습니다.  이번 릴리스에서는 정규식을 사용하여 개인 패턴을 추가하는 기능이 BlueXP classification UI에 추가되어 이러한 사용자 정의 패턴을 매우 쉽게 추가하고 편집할 수 있습니다.

.BlueXP classification 사용하여 1,500만 개의 파일을 이동할 수 있는 기능
과거에는 BlueXP classification 최대 100,000개의 소스 파일을 모든 NFS 공유로 옮길 수 있었습니다.  이제 최대 1,500만 개의 파일을 한 번에 이동할 수 있습니다.

.SharePoint Online 파일에 액세스할 수 있는 사용자 수를 볼 수 있는 기능
"액세스 권한이 있는 사용자 수" 필터는 이제 SharePoint Online 저장소에 저장된 파일을 지원합니다.  과거에는 CIFS 공유에 있는 파일만 지원되었습니다.  현재 Active Directory 기반이 아닌 SharePoint 그룹은 이 필터에 포함되지 않습니다.

.새로운 "부분적 성공" 상태가 작업 상태 패널에 추가되었습니다.
새로운 "부분적 성공" 상태는 BlueXP classification 작업이 완료되었고 일부 항목은 실패하고 일부 항목은 성공했음을 나타냅니다. 예를 들어, 100개의 파일을 이동하거나 삭제할 때입니다.  또한, "완료" 상태의 이름이 "성공"으로 변경되었습니다.  과거에는 "완료" 상태에 성공한 작업과 실패한 작업이 나열되었습니다.  이제 "성공" 상태는 모든 항목에 대한 모든 작업이 성공했음을 의미합니다. https://docs.netapp.com/us-en/data-services-data-classification/task-view-compliance-actions.html["작업 상태 패널을 보는 방법을 확인하세요."] .



== 2023년 1월 9일



=== 버전 1.19

.민감한 데이터가 포함되어 있고 지나치게 허용적인 파일 차트를 볼 수 있는 기능
거버넌스 대시보드에 새로운 _민감한 데이터 및 광범위한 권한_ 영역이 추가되었는데, 이 영역은 민감한 데이터(민감한 데이터와 민감한 개인 데이터 모두 포함)를 포함하고 지나치게 권한이 부여된 파일의 히트맵을 제공합니다.  이를 통해 민감한 데이터와 관련하여 어떤 위험이 있는지 파악하는 데 도움이 될 수 있습니다. https://docs.netapp.com/us-en/data-services-data-classification/task-controlling-governance-data.html["자세히 알아보기"] .

.데이터 조사 페이지에서 세 가지 새로운 필터를 사용할 수 있습니다.
데이터 조사 페이지에 표시되는 결과를 구체화하기 위해 새로운 필터를 사용할 수 있습니다.

* "액세스 권한이 있는 사용자 수" 필터는 특정 수의 사용자에게 열려 있는 파일과 폴더를 보여줍니다.  결과를 구체화하기 위해 숫자 범위를 선택할 수 있습니다. 예를 들어, 51~100명의 사용자가 접근할 수 있는 파일을 확인할 수 있습니다.
* 이제 "생성 시간", "검색 시간", "마지막 수정" 및 "마지막 액세스" 필터를 사용하여 미리 정의된 날짜 범위를 선택하는 대신 사용자 지정 날짜 범위를 만들 수 있습니다.  예를 들어, "생성 시간"이 "6개월 이상"인 파일이나 "마지막 수정 날짜"가 "지난 10일 이내"인 파일을 찾을 수 있습니다.
* 이제 "파일 경로" 필터를 사용하여 필터링된 쿼리 결과에서 제외할 경로를 지정할 수 있습니다.  특정 데이터를 포함하고 제외하는 경로를 입력하면 BlueXP classification 먼저 포함된 경로에 있는 모든 파일을 찾은 다음, 제외된 경로에서 파일을 제거한 다음 결과를 표시합니다.


https://docs.netapp.com/us-en/data-services-data-classification/task-investigate-data.html["데이터를 조사하는 데 사용할 수 있는 모든 필터 목록을 확인하세요."] .

.BlueXP classification 일본 개인 번호를 식별할 수 있습니다.
BlueXP classification 일본 개인 번호(마이 넘버라고도 함)가 포함된 파일을 식별하고 분류할 수 있습니다.  여기에는 개인 및 회사 내 번호가 모두 포함됩니다. https://docs.netapp.com/us-en/data-services-data-classification/reference-private-data-categories.html["BlueXP classification 귀하의 데이터에서 식별할 수 있는 모든 유형의 개인 데이터를 확인하세요."] .
