= 버전 1.40
:allow-uri-read: 




=== 버전 1.40

이 BlueXP classification 릴리스에는 다음과 같은 업데이트가 포함되어 있습니다.

.RHEL 9.5 지원
이 릴리스에서는 이전에 지원되었던 버전 외에도 Red Hat Enterprise Linux v9.5에 대한 지원이 제공됩니다. 이는 다크 사이트 배포를 포함하여 BlueXP classification 의 모든 수동 온프레미스 설치에 적용됩니다.

다음 운영 체제에서는 Podman 컨테이너 엔진을 사용해야 하며, BlueXP classification 버전 1.30 이상이 필요합니다: Red Hat Enterprise Linux 버전 8.8, 8.10, 9.0, 9.1, 9.2, 9.3, 9.4 및 9.5.

.스캔 우선 순위 지정
구성을 스캔할 때 가장 중요한 스캔의 우선순위를 지정하여 다른 스캔보다 먼저 수행할 수 있습니다.  이 기능은 작업 환경이 여러 개인 경우, 우선 순위가 높은 스캔이 처음에 성공적으로 수행되도록 하려는 경우에 도움이 됩니다.

스캔에는 두 가지 유형이 있습니다.

* *매핑 전용 스캔*은 데이터에 대한 개략적인 개요만 제공합니다.  데이터 내부에 있는 데이터를 보기 위해 파일에 접근하지 않기 때문에 데이터 소스에서 매우 빠르게 매핑을 수행할 수 있습니다.
* *매핑 및 분류* 스캔은 데이터에 대한 심층적인 스캔을 제공합니다.


매핑 전용 스캔을 사용하면 데이터를 빠르게 스캔하여 추가 조사가 필요한 데이터 소스를 식별한 다음 나중에 필요한 데이터 소스나 볼륨에 대해서만 매핑 및 분류 스캔을 활성화하는 것이 좋습니다.

우선순위는 매핑 전용 스캔에만 지정되고, 매핑 및 분류 스캔에는 지정되지 않습니다.

우선순위는 기본적으로 1로 설정되어 있으며, 1~10 사이의 숫자로 변경할 수 있습니다.  숫자가 낮을수록 우선순위가 높습니다.  우선순위를 설정하지 않으면 스캔에 우선순위 5가 지정됩니다.

우선순위를 변경하려면 다음을 수행하세요.

. BlueXP classification 메뉴에서 *구성*을 선택합니다.
. 우선순위를 지정할 리소스를 선택하세요.
. 작업... 옵션에서 *스캔 우선순위 지정*을 선택합니다.


.스캔 재시도
이 릴리스에서는 실패한 검사를 다시 시도할 수 있습니다.  이 기능은 네트워크 중단과 같은 일시적인 문제로 인해 검사에 실패했을 때 유용합니다.  다시 구성하지 않고도 검사를 다시 시도할 수 있습니다.

스캔을 다시 시도하려면 다음을 수행하세요.

. BlueXP classification 메뉴에서 *구성*을 선택합니다.
. 다음 중 하나를 수행하세요.
+
** 실패한 모든 검사를 다시 시도하려면 *모든 검사 다시 시도*를 선택하세요.
** 특정 검사를 다시 시도하려면 리소스를 선택하고 작업... 옵션에서 *검사 다시 시도*를 선택하세요.




원래 스캔과 동일한 구성으로 스캔을 다시 시도합니다.  검사가 다시 실패하면 필요한 만큼 다시 시도할 수 있습니다.
