= 버전 1.43
:allow-uri-read: 




=== 버전 1.43

이 데이터 분류 릴리스에는 다음이 포함됩니다.

.분류 스캔 우선 순위 지정
데이터 분류는 매핑 전용 스캔 외에도 맵 및 분류 스캔의 우선순위를 지정하는 기능을 지원하여 어떤 스캔을 먼저 완료할지 선택할 수 있습니다.  Map & Classify 스캔의 우선순위 지정은 스캔이 시작되기 전과 시작 중 지원됩니다.  검사가 진행되는 동안 검사의 우선순위를 지정하는 경우 매핑 검사와 분류 검사가 모두 우선순위가 지정됩니다.

자세한 내용은 다음을 참조하세요. link:https://docs.netapp.com/us-en/bluexp-classification/task-managing-repo-scanning.html#prioritize-scans["스캔 우선 순위 지정"] .

.캐나다 개인 식별 정보(PII) 데이터 범주 지원
데이터 분류 스캔은 캐나다 PII 데이터 범주를 식별합니다.  이러한 범주에는 모든 캐나다 주와 지역의 은행 정보, 여권 번호, 사회보장번호, 운전면허증 번호, 건강카드 번호가 포함됩니다.

자세한 내용은 다음을 참조하세요. link:https://docs.netapp.com/us-en/bluexp-classification/reference-private-data-categories.html#types-of-personal-data["개인 데이터 범주"] .

.사용자 정의 분류(미리 보기)
데이터 분류는 Map & Classify 스캔에 대한 사용자 정의 분류를 지원합니다.  사용자 정의 분류를 사용하면 정규 표현식을 사용하여 조직에 맞는 데이터를 캡처하도록 데이터 분류 검사를 맞춤화할 수 있습니다.  이 기능은 현재 미리보기 단계에 있습니다.

자세한 내용은 다음을 참조하세요. link:https://docs.netapp.com/us-en/bluexp-classification/task-custom-classification.html["사용자 정의 분류 추가"] .

.저장된 쿼리 탭
**정책** 탭의 이름이 변경되었습니다.link:https://docs.netapp.com/us-en/bluexp-classification/task-using-policies.html["**저장된 쿼리**"] .  기능은 변경되지 않았습니다.

.감사 페이지로 스캔 이벤트 보내기
데이터 분류는 분류 이벤트(스캔이 시작될 때와 종료될 때)를 전송하는 것을 지원합니다.link:https://docs.netapp.com/us-en/bluexp-setup-admin/task-monitor-cm-operations.html#audit-user-activity-from-the-bluexp-timeline["NetApp Consle Audit 페이지"^] .

.보안 업데이트
* Keras 패키지가 업데이트되어 취약점(BDSA-2025-0107 및 BDSA-2025-1984)이 완화되었습니다.
* Docker 컨테이너 구성이 업데이트되었습니다.  컨테이너는 더 이상 원시 네트워크 패킷을 제작하기 위해 호스트의 네트워크 인터페이스에 액세스할 수 없습니다.  불필요한 접근을 줄임으로써 업데이트를 통해 잠재적인 보안 위험이 완화됩니다.


.성능 향상
RAM 사용량을 줄이고 데이터 분류의 전반적인 성능을 개선하기 위해 코드 개선이 구현되었습니다.

.버그 수정
StorageGRID 검사가 실패하고, 조사 페이지 필터 옵션이 로드되지 않으며, 대용량 평가의 경우 데이터 검색 평가가 다운로드되지 않는 버그가 수정되었습니다.
